### PR TITLE
Various bug fixes, minor improvements, and basic skinning/theming support

### PR DESCRIPTION
**Pull request by smkent**
In the process of installing CGP on my own server, I've made a number of minor bug fixes and improvements that are useful to me. The biggest change is adding basic skinning/theming support, as I wanted a theme (and graphs) with darker backgrounds to be easier on my eyes.

Feel free to pull in whichever of these you find useful.

Some example screenshots:

Adding load average HRULEs based on # of CPUs:

hrule

Another example of custom skin colors:

mem

Graphing arbitrary data from collectd's exec plugin:

exec

Highlight on the ping graph when no response received:

ping_highlight

### CODE REVIEW

**Comment by smkent** [comment]
I am slowly rebasing my branch. A lot has changed upstream so I have to rewrite a bit. I'll update when it's ready to go again.

**Comment by smkent** [comment]
I've updated my branch. My additional commits are now based on the current upstream branch.

**Comment by Lekensteyn** [comment]
Quick review, minor nits: spaces vs. tabs. See comments above.

**Comment by smkent** [comment]
@Lekensteyn, thanks for the feedback. I have made your suggested changes and updated my branch.

**Comment by smkent** [comment]
Rebased to latest master again. jsrrdgraph [fixed the bug](https://github.com/manuelluis/jsrrdgraph/pull/21) I included a fix for in an earlier version of this pull request, so that commit has been removed.

**Pull request closed without merging**
